### ISSUE TITLE
After a recent merge, gcs_inventory load fails with an error: "configparser.NoSectionError: No section: 'GCP'

### ISSUE THREAD

**Issue by sghosh-discovery** [domZippilli/gcs-inventory-loader#9]
gcs_inventory load <bucket> does not work any more for me after I copied the latest code.
Configuration parsed: 

```
Log level is INFO, set by default
Traceback (most recent call last):
  File "/home/sourav_ghosh/.local/bin/gcs_inventory", line 8, in <module>
    sys.exit(main())
  File "/home/sourav_ghosh/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sourav_ghosh/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sourav_ghosh/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sourav_ghosh/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sourav_ghosh/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sourav_ghosh/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sourav_ghosh/.local/lib/python3.9/site-packages/gcs_inventory_loader/__init__.py", line 94, in load
    return load_command(buckets, prefix)
  File "/home/sourav_ghosh/.local/lib/python3.9/site-packages/gcs_inventory_loader/cli/load.py", line 47, in load_command
    gcs = get_gcs_client()
  File "/home/sourav_ghosh/.local/lib/python3.9/site-packages/gcs_inventory_loader/gcs/client.py", line 74, in get_gcs_client
    return CLIENTS.get_client()
  File "/home/sourav_ghosh/.local/lib/python3.9/site-packages/gcs_inventory_loader/gcs/client.py", line 54, in get_client
    fallback=config.get('GCP', 'PROJECT'))))
  File "/usr/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.9/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'GCP'
```

**Comment by domZippilli** [comment]
I'm not able to reproduce this error without modifying or deleting the `[GCP]` section header in the config file. Can you double-check your config file and make sure it has one like [this](https://github.com/domZippilli/gcs-inventory-loader/blob/b1bca268d49fc4c70828c9c8d571fbfbb460ae9b/default.cfg#L16)? 

The error seems to be happening in `client.py` which has only had very minor [linting](https://github.com/domZippilli/gcs-inventory-loader/commit/2eeb22e4daf7255ca96eb5268d322762229a9aac#diff-0a6cd5a716dc7c401c0c4c16b07617da8170224b16259fa60416d139cf87a53a) since 2020, so it's not immediately clear what recent changes would relate.

**Comment by domZippilli** [comment]
Following up -- talked to @sghosh-discovery off-thread and this issue is resolved.
